In [1]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import animation
import time
%matplotlib notebook
#generate train data
xdata = np.random.uniform(-5, 5, (2, 100))
ydata = np.sign(xdata[0, :] * xdata[1, :])

#generate test data
xtest = np.random.uniform(-5, 5, (2, 100))
ytest = np.sign(xtest[0, :] * xtest[1, :])

# activation function
def tanh(x):
    return np.tanh(x)

# derivative of activation function
def tanh_deriv(x):
    return 1.0 - np.tanh(x)**2

# loss function
def loss(y, yhat):
    return np.mean((y - yhat)**2)

# derivative of loss function
def loss_deriv(y, yhat):
    return 2 * (yhat - y) / y.size

#test data loss
def test():
    global xtest, ytest, w1, w2, b1
    yhat, _ = output(xtest, w1, w2, b1)
    return loss(ytest, yhat)

# initialize weights
w1 = np.random.uniform(-1, 1, (2, 4))
w2 = np.random.uniform(-1, 1, (4, 1))
b1 = np.random.uniform(-1, 1, (4, 1))

def output(x, w1, w2, b1):
    # forward pass
    z1 = np.dot(w1.T, x) + b1
    a1 = tanh(z1)
    z2 = np.dot(w2.T, a1)
    yhat = tanh(z2)
    return yhat, a1

def random(shape):
    return np.sign(np.random.uniform(-0.8, 0.2, shape))*0.5 + 0.5



def update(x, y, w1, w2, b1, lr):
    #randomly select 20% of the data
    idx = np.random.choice(x.shape[1], int(x.shape[1] * 0.7), replace=False)
    x = x[:, idx]
    y = y[idx]
    # forward pass
    yhat, a1 = output(x, w1, w2, b1)
    # backward pass
    delta2 = loss_deriv(y, yhat) * tanh_deriv(yhat)
    delta1 = tanh_deriv(a1) * np.dot(w2, delta2)
    # update weights
    w2 -= lr * np.dot(a1, delta2.T)*random(w2.shape)
    w1 -= lr * np.dot(x, delta1.T)*random(w1.shape)
    b1 -= lr * np.sum(delta1)*random(b1.shape)
    return w1, w2, b1




x = np.linspace(-5, 5, 100)
y = np.linspace(-5, 5, 100)
X, Y = np.meshgrid(x, y)

lossarray = []

def animate(i):
    global xdata, ydata, w1, w2, b1
    for i in range(100):
        w1, w2, b1 = update(xdata, ydata, w1, w2, b1, 0.005)
    
    yhat, _ = output(xdata, w1, w2, b1)
    print(str(w1) + " " + str(w2) + " " + str(b1) + " " + str(loss(ydata, yhat)), end='\r')
    time.sleep(0)
    
    plt.cla()
    Z = output(np.array([X.ravel(), Y.ravel()]), w1, w2, b1)[0].reshape(X.shape)
    plt.pcolor(X, Y, Z, cmap='RdBu')
    plt.scatter(xdata[0, :], xdata[1, :], c=ydata, cmap='RdBu')
    plt.title('Loss: %.4f' % loss(ydata, yhat) + ' Test Loss: %.4f' % test())
 
    plt.xlim(-5, 5)
    plt.ylim(-5, 5)
    lossarray.append(loss(ydata, yhat))




fig = plt.figure()
ani = animation.FuncAnimation(fig, animate, 500,  interval=10)
fn = 'neuro0006'
ani.save(fn+'.gif',writer='ffmpeg')
plt.rcParams['animation.html'] = 'html5'
ani










<IPython.core.display.Javascript object>

[[-0.20891379 -0.458868    0.0201996  -0.78434181]
 [-0.93475856 -0.50312595  0.52366653 -0.60311642]] [[ 0.13811059]
 [-0.91266889]
 [ 0.67453052]
 [ 0.0643378 ]] [[ 0.36612242]
 [-0.02195588]
 [ 0.27586497]
[[-0.21143581 -0.44624405 -0.0411243  -0.78689332]
 [-0.95284711 -0.39075921  0.43518442 -0.60924962]] [[ 0.19801453]
 [-0.87676598]
 [ 0.60078285]
 [ 0.06939129]] [[ 0.38722971]
 [-0.00751245]
 [ 0.28870976]
[[-0.2150584  -0.43533432 -0.10187727 -0.79053749]
 [-0.97008109 -0.31820652  0.36513979 -0.61485569]] [[ 0.2478243 ]
 [-0.84358135]
 [ 0.54422453]
 [ 0.07416492]] [[0.40998809]
 [0.0166828 ]
 [0.30488593]
[[-0.21913565 -0.40958626 -0.15706243 -0.79712369]
 [-0.99156356 -0.23648583  0.30173425 -0.62287339]] [[ 0.28935849]
 [-0.80549362]
 [ 0.51145163]
 [ 0.07149873]] [[0.42385374]
 [0.04175483]
 [0.32559507]
[[-0.22507746 -0.36851482 -0.19930798 -0.79995225]
 [-1.01476369 -0.18486309  0.23390574 -0.62579998]] [[ 0.32532373]
 [-0.77902091]
 [ 0.50281068]
 [ 0.05839912]] [[0.44