In [1]:
import numpy as np
import matplotlib.pyplot as plt
def machineEpsilon(func=np.float64):
    machine_epsilon = func(1)
    while func(1)+machine_epsilon != func(1):
        machine_epsilon_last = machine_epsilon
        machine_epsilon = func(machine_epsilon) / func(2)
    return machine_epsilon_last

sqeps = np.sqrt(machineEpsilon())

In [46]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib widget

x = np.array([0, 25, 50, 75, 100, 125, 150, 175, 200])
y = np.array([10.6, 16.0, 45.0, 83.5, 52.8, 19.9, 10.8, 8.25, 4.7])
rho = np.array([2.3, 3.5, 4.5, 6.4, 4.4, 3.4, 2.1, 1.6, 1.1])

#starting valuse
a = np.array([60000, 70, 750])

#fitting function breit wigner
def f(x, a):
    return a[0]/((a[1] - x)**2 + a[2])

#function to calculate the chi2
def chi2(x, y, rho, a):
    return np.sum(((y - f(x, a))/rho)**2)

#beta

def beta(chi2, x, y, a, rho, h=sqeps):
    j = np.zeros(len(a))
    ak = np.zeros(len(a))
    for i in range(len(a)):
        ak[i] = np.sum((y - f(x, a))/rho**2 * (f(x, a+ h*a[i] * np.eye(len(a))[i]) - f(x, a - h*a[i] * np.eye(len(a))[i]))/(2*h*a[i]))
    return ak

# alpha

def alpha(chi2, x, y, a, rho, h=sqeps):
    ap = np.zeros((len(a), len(a)))
    for i in range(len(a)):
        for j in range(len(a)):
            ap[i, j] = np.sum(((f(x, a + h*a[i] * np.eye(len(a))[i]) - f(x, a - h*a[i] * np.eye(len(a))[i]))/(2*h*a[i]) * (f(x, a + h*a[i] * np.eye(len(a))[j]) - f(x, a - h*a[i] * np.eye(len(a))[j]))/(2*h*a[i])/rho**2))
    return ap

#newton step

def newton_step(chi2, x, y, a, rho, h=sqeps):
    anew = a + np.linalg.pinv(alpha(chi2, x, y, a, rho, h)) @ beta(chi2, x, y, a, rho, h)
    return anew

print(alpha(chi2, x, y, a, rho))
print(beta(chi2, x, y, a, rho))


[[ 1.29459385e-07 -1.25684743e-05 -6.23420097e-06]
 [-1.25681185e-05  3.62391850e-01  4.21734690e-04]
 [-6.23420038e-06  4.21734511e-04  3.77938793e-04]]
[ 5.65729703e-04  2.66545297e+00 -1.67253945e-02]


In [47]:

chilist = []
alist = []
for i in range(3):
    a = newton_step(chi2, x, y, a, rho)
    alist.append(a)
    chilist.append(chi2(x, y, rho, a))

for i in range(100):
    a = newton_step(chi2, x, y, a, rho)
    chilist.append(chi2(x, y, rho, a))
    alist.append(a)
    # if np.abs(chilist[-1] - chilist[-2]) <= np.abs(chilist[-2] * 1e-6):
    #     break

#return minimum chi2
print(min([abs(i) for i in chilist]))


print(alist[[abs(i) for i in chilist].index(min([abs(i) for i in chilist]))])


print(chilist)
print(a)



2.7023271328659364
[68310.00237878    77.57646324   807.87147937]
[3.4070532099832804, 2.7069717182821997, 2.7023278182108417, 2.7023271329368144, 2.7023271328659484, 2.7023271328659417, 2.702327132865939, 2.7023271328659395, 2.7023271328659413, 2.7023271328659404, 2.702327132865941, 2.70232713286594, 2.702327132865942, 2.702327132865943, 2.702327132865941, 2.7023271328659417, 2.7023271328659404, 2.702327132865945, 2.7023271328659417, 2.7023271328659413, 2.702327132865941, 2.7023271328659417, 2.7023271328659417, 2.7023271328659413, 2.7023271328659417, 2.7023271328659435, 2.702327132865941, 2.7023271328659435, 2.702327132865939, 2.702327132865943, 2.70232713286594, 2.7023271328659404, 2.7023271328659435, 2.7023271328659386, 2.702327132865939, 2.702327132865942, 2.702327132865941, 2.702327132865941, 2.7023271328659395, 2.7023271328659404, 2.702327132865939, 2.7023271328659377, 2.702327132865941, 2.70232713286594, 2.7023271328659417, 2.702327132865942, 2.70232713286594, 2.702327132865939,

In [57]:
#levenberg step
a = np.array([60, 70, 4])
alev = []
chilev = []
def ltep(chi2, x, y, a, rho, lam, h=sqeps):
    anew = a + (np.linalg.pinv(alpha(chi2, x, y, a, rho, h) + lam * np.diag(np.diag(alpha(chi2, x, y, a, rho, h)))) @ beta(chi2, x, y, a, rho, h))
    return anew



lam = 1.0


for i in range(1000):
    anew = ltep(chi2, x, y, a, rho, lam)
    print(f"step {i}")
    print(chi2(x, y, rho, a), chi2(x, y, rho, anew))
    

    if abs(chi2(x, y, rho, anew)) < abs(chi2(x, y, rho, a)):
        a = anew
        lam = lam/10
        print(lam)
        alev.append(a)
        chilev.append(chi2(x, y, rho, a))
        
    else:
        lam = lam*10
        print(lam)
        if lam > 1e10:
            break

print(min([abs(i) for i in chilev]))
print(alev[[abs(i) for i in chilev].index(min([abs(i) for i in chilev]))])

print(chilev)
print(alev)

step 0
552.2534150674171 528.4950409050128
0.1
step 1
528.4950409050128 736.4151900819757
1.0
step 2
528.4950409050128 582.2325081905395
10.0
step 3
528.4950409050128 501.0412135255731
1.0
step 4
501.0412135255731 417.8722403155951
0.1
step 5
417.8722403155951 401.5285125303564
0.01
step 6
401.5285125303564 386.0546799019895
0.001
step 7
386.0546799019895 367.0137704892645
0.0001
step 8
367.0137704892645 410.52569004311016
0.001
step 9
367.0137704892645 522.6279514193291
0.01
step 10
367.0137704892645 330.02287453413174
0.001
step 11
330.02287453413174 225.87597929654572
0.0001
step 12
225.87597929654572 38.90260070515597
1e-05
step 13
38.90260070515597 5.581084505773098
1.0000000000000002e-06
step 14
5.581084505773098 2.7213503374674426
1.0000000000000002e-07
step 15
2.7213503374674426 2.7023305000145634
1.0000000000000002e-08
step 16
2.7023305000145634 2.702327133143086
1.0000000000000003e-09
step 17
2.702327133143086 2.7023271328659733
1.0000000000000003e-10
step 18
2.70232713286597